# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (Latest image)
        id: meta_latest
        uses: docker/metadata-action@v3
        with:
          images: lambda3/azure-pipelines-agent
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./agent/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_latest.outputs.tags }}
          labels: ${{ steps.meta_latest.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (Docker image)
        id: meta_docker
        uses: docker/metadata-action@v3
        with:
          images: lambda3/azure-pipelines-agent
          flavor: |
            latest=false
          tags: |
            type=raw,value=docker,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,suffix=-docker,event=tag

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./agent-docker/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_docker.outputs.tags }}
          labels: ${{ steps.meta_docker.outputs.labels }}
